### ISSUE TITLE
starwars dataset issue

### ISSUE THREAD

**Issue by EastBayEv** [dlab-berkeley/advanced-data-wrangling-in-R#30]

**Comment by asteves** [comment]
What's the issue? @EastBayEv

**Comment by Akesari12** [comment]
The original issue is that the original starwars dataset had a column called gender that used "male", "female", and "hermaphroditic" for each character (with the last one only being for Jabba the Hutt). The term "hermaphrodite" is insensitive/offensive, so I was concerned about its use. The dataset has since been updated so that this column has been renamed sex, and there is now a gender column that uses "masculine" and "feminine" as values. In the code in the workshop, we only filter on this new column, so maybe we don't need changes, but I'd be curious to hear others' thoughts.

**Comment by asteves** [comment]
@Akesari12 My view is that we should strive to have a dataset that doesn't run into the issue you raise. I agree with your description of the term as offensive. I'm also not clear personally if masculine/feminine is correct for a gender column either. 

There's the [Palmer's Penguins dataset](https://allisonhorst.github.io/palmerpenguins/articles/intro.html) that could work equally as well as a general dataset, and it might be worth asking if it's even worth demonstrating subsetting on a binary variable for a concept that is not binary. 

Thoughts?

**Comment by asteves** [comment]
To add just a bit, I think it is also worth using the same data consistently throughout the workshop for pedagogical reasons. However, there are also pedagogical reasons to show different data for interest. 

The materials currently have multiple datasets throughout, so subbing in a single dataset is not a problem for any single question. It is more work, but possibly worthy work, to change every example to work with the same dataset.

**Comment by Akesari12** [comment]
I like the idea of switching over to Penguins for at least this example. Also agreed on maybe streamlining with one dataset throughout. I think swapping starwars for penguins is doable before the next iteration, and then we do a bigger refresh over the summer?

**Comment by asteves** [comment]
I've updated in the develop branch to remove the Star Wars data entirely and replace it with Penguins. I've also made it so that the 02 branch uses the penguins dataset throughout. All of the underlying examples remain the same, but of course some specific details will change.

**Comment by Akesari12** [comment]
Merged in the branch that updates 01 and 02 - let's make a new issue for using penguins throughout the workshop. Thanks @asteves !
