### ISSUE TITLE
02-subsetting.Rmd Challenge #2 scripting

### ISSUE THREAD

**Issue by Averysaurus** [dlab-berkeley/advanced-data-wrangling-in-R#31]
the chunk above the ***Challenge 1*** script there is the answer. Need to cut/paste the rmd text to go above the chunk 85-91.

Also consider adding to the narrative in line 98, something like:

* filter() based on character strings*

**Comment by asteves** [comment]
@Averysaurus With respect to the first point, Can you be more specific on what you mean by answer here?

`starwars %>%
  filter(height < 180 | height > 160) %>%
  nrow()`

is not a correct answer to the challenge: 

"1. (1) Use `filter(between())` to find characters whose heights are between 180 and 160 and (2) count the number of these observations." 

because it doesn't include a call to `between()`

**Comment by Averysaurus** [comment]
heck I missed that part, thanks nevermind. :)
