### ISSUE TITLE
New example for non-tidy data analysis?

### ISSUE THREAD

**Issue by Averysaurus** [dlab-berkeley/advanced-data-wrangling-in-R#41]
on line 72 or so, we reference that  Principal Component Analysis (PCA) does not jive with tidy approaches so well. Recently learned that's not so true! 

[Take a look here](https://juliasilge.com/blog/cocktail-recipes-umap/)

**Comment by asteves** [comment]
Which R file?

**Comment by Averysaurus** [comment]
01-reshaping.

**Comment by asteves** [comment]
I see  now. The file is referencing that tidy data will impose a time cost penalty for the computation because it's not in matrix format initially. That is still true. 

The tidymodels post you reference is cool, but does seem beyond the content of this workshop. I'll make a small tweak in the language to reflect this.

**Comment by asteves** [comment]
Closed in latest pull request
